---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagger
  namespace: tagger
  labels:
    app: tagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tagger
  template:
    metadata:
      labels:
        app: tagger
    spec:
      serviceAccountName: tagger
      containers:
      - name: tagger
        image: quay.io/rmarasch/tagger:latest
        volumeMounts:
          - mountPath: "/assets"
            name: certs
            readOnly: true
        ports:
        - containerPort: 8080
        env:
        - name: CACHE_REGISTRY_INSECURE
          value: "true"
        - name: CACHE_REGISTRY_ADDRESS
          value: "goiaba.news:5000"
        - name: CACHE_REGISTRY_USERNAME
          value: "rmarasch"
        - name: CACHE_REGISTRY_PASSWORD
          value: "rmarasch"
      volumes:
      - name: certs
        secret:
          secretName: certs
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhooks
  namespace: tagger
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quay-webhooks 
  namespace: tagger
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8081 
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: docker-webhooks 
  namespace: tagger
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8082 
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: tagio
  namespace: tagger
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: tagger
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
